services:

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://52.201.214.88:5000
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:3001"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: unless-stopped

  chatbot:
    build: ./fastcube-chatbot
    container_name: chatbot-service
    ports:
      - "8001:8001"
    env_file:
      - ./fastcube-chatbot/.env
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastcube
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data: